farm:
	@npx hardhat run scripts/deployments/deploy_c2n_token.ts --network localhost
	@npx hardhat run scripts/deployments/deploy_airdrop_c2n.ts --network localhost
	@npx hardhat run scripts/deployments/deploy_farm.ts --network localhost

