basePath: /api/v1
definitions:
  request.GetTokenRequest:
    properties:
      address:
        type: string
      signature:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/token:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add account
        in: body
        name: GetToken
        required: true
        schema:
          $ref: '#/definitions/request.GetTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
